package com.nithra.nithraresume.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light scheme ──────────────────────────────────────────────────────────────
val md_light_primary             = Color(0xFF1565C0) // Blue 800
val md_light_onPrimary           = Color(0xFFFFFFFF)
val md_light_primaryContainer    = Color(0xFFD3E4FF)
val md_light_onPrimaryContainer  = Color(0xFF001B3E)
val md_light_secondary           = Color(0xFF545F70)
val md_light_onSecondary         = Color(0xFFFFFFFF)
val md_light_secondaryContainer  = Color(0xFFD8E3F8)
val md_light_onSecondaryContainer = Color(0xFF111C2B)
val md_light_tertiary            = Color(0xFF6C5677)
val md_light_onTertiary          = Color(0xFFFFFFFF)
val md_light_tertiaryContainer   = Color(0xFFF4D9FF)
val md_light_onTertiaryContainer = Color(0xFF261430)
val md_light_error               = Color(0xFFBA1A1A)
val md_light_onError             = Color(0xFFFFFFFF)
val md_light_errorContainer      = Color(0xFFFFDAD6)
val md_light_onErrorContainer    = Color(0xFF410002)
val md_light_background          = Color(0xFFF8F9FF)
val md_light_onBackground        = Color(0xFF191C20)
val md_light_surface             = Color(0xFFF8F9FF)
val md_light_onSurface           = Color(0xFF191C20)
val md_light_surfaceVariant      = Color(0xFFDFE2EB)
val md_light_onSurfaceVariant    = Color(0xFF43474E)
val md_light_outline             = Color(0xFF73777F)
val md_light_outlineVariant      = Color(0xFFC3C6CF)
val md_light_scrim               = Color(0xFF000000)
val md_light_inverseSurface      = Color(0xFF2E3135)
val md_light_inverseOnSurface    = Color(0xFFEFF0F7)
val md_light_inversePrimary      = Color(0xFFA4C8FF)

// ── Dark scheme ───────────────────────────────────────────────────────────────
val md_dark_primary              = Color(0xFFA4C8FF)
val md_dark_onPrimary            = Color(0xFF002F65)
val md_dark_primaryContainer     = Color(0xFF004494)
val md_dark_onPrimaryContainer   = Color(0xFFD3E4FF)
val md_dark_secondary            = Color(0xFFBCC7DB)
val md_dark_onSecondary          = Color(0xFF263141)
val md_dark_secondaryContainer   = Color(0xFF3C4758)
val md_dark_onSecondaryContainer = Color(0xFFD8E3F8)
val md_dark_tertiary             = Color(0xFFD8BCE5)
val md_dark_onTertiary           = Color(0xFF3A2945)
val md_dark_tertiaryContainer    = Color(0xFF523F5D)
val md_dark_onTertiaryContainer  = Color(0xFFF4D9FF)
val md_dark_error                = Color(0xFFFFB4AB)
val md_dark_onError              = Color(0xFF690005)
val md_dark_errorContainer       = Color(0xFF93000A)
val md_dark_onErrorContainer     = Color(0xFFFFDAD6)
val md_dark_background           = Color(0xFF111318)
val md_dark_onBackground         = Color(0xFFE2E2E9)
val md_dark_surface              = Color(0xFF111318)
val md_dark_onSurface            = Color(0xFFE2E2E9)
val md_dark_surfaceVariant       = Color(0xFF43474E)
val md_dark_onSurfaceVariant     = Color(0xFFC3C6CF)
val md_dark_outline              = Color(0xFF8D9199)
val md_dark_outlineVariant       = Color(0xFF43474E)
val md_dark_scrim                = Color(0xFF000000)
val md_dark_inverseSurface       = Color(0xFFE2E2E9)
val md_dark_inverseOnSurface     = Color(0xFF2E3135)
val md_dark_inversePrimary       = Color(0xFF1565C0)
